steps:
- id: 'Pull Terraform Image'
  name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/terraform:latest || exit 0']

- id: 'Build Terraform Image'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--tag=gcr.io/${PROJECT_ID}/terraform',
    '--build-arg=TERRAFORM_VERSION=${_TERRAFORM_VERSION}',
    '--build-arg=TERRAFORM_VERSION_SHA256SUM=${_TERRAFORM_VERSION_SHA256SUM}',
    '--build-arg=TERRAFORM_VALIDATOR_RELEASE=${_TERRAFORM_VALIDATOR_RELEASE}',
    '--cache-from', 'gcr.io/$PROJECT_ID/terraform:latest',
    '.'
    ]

- id: 'Enabling APIs'
  name: 'gcr.io/${PROJECT_ID}/terraform'
  entrypoint: /bin/bash
  args:
  - -c
  - |
     gcloud services enable compute.googleapis.com

- id: 'Executing Terraform Init'
  name: 'gcr.io/${PROJECT_ID}/terraform'
  entrypoint: /bin/bash
  args:
  - -c
  - |
      echo "Update the project ID"
      sed -i 's\_PROJECT_ID_\${PROJECT_ID}\g' main.tf
      echo "Update backend bucket"
      sed -i 's\_BUCKET_STATE_\${_BUCKET_STATE}\g' backend.tf
      echo "Change permission for entrypoint.bash"
      chmod +x entrypoint.bash
      echo "Running Terraform init"
      terraform init ; terraform ${_TF_ACTION}

substitutions:
  _TERRAFORM_VERSION: '0.13.6' # default value
  _TERRAFORM_VERSION_SHA256SUM: '55f2db00b05675026be9c898bdd3e8230ff0c5c78dd12d743ca38032092abfc9'
  _TERRAFORM_VALIDATOR_RELEASE: '2021-03-22'
    
images: ['gcr.io/${PROJECT_ID}/terraform']
